#!/usr/bin/perl
$| = 1;

#print "Scanning for local apache directories to restart if needed...\n";

opendir( DIR, "/local" );
while ( $file = readdir(DIR) )
{
	if ( $file eq "apache-root" || $file =~ /apache-root-.*/ )
	{
		if ( -e "/local/$file/reload" )
		{
			&check_dir("/local/$file");
		}
	}
}
closedir(DIR);

sub mysystem
{
	my ($cmd) = @_;
	print "+ $cmd\n";
	system($cmd);
}

sub check_dir
{
	my $dir          = shift;
	my $need_restart = 0;

	foreach my $file ( "error_log.today", "error_log" )
	{
		open( IN, "$dir/logs/$file" );
		while ( $line = <IN> )
		{
			if ( $line =~ /Segmentation fault/o )
			{
				if ( $need_restart != 1 )
				{
					#print "Found segfault indicator in $dir/logs/$file.\n";
				}
				$need_restart = 1;
			}
			elsif ( $line =~ /resuming normal operations/o )
			{
				if ( $need_restart != 0 )
				{
					#print "Found restart indicator in $dir/logs/$file.\n";
				}
				$need_restart = 0;
			}
		}
		close(IN);
	}

	if ( -e "$dir/logs/pidfile" )
	{
		my $pid;
		open(IN, "$dir/logs/pidfile");
		chomp($pid = <IN>);

		if ( kill(0, $pid) == 0 )
		{
			$need_restart = 1;
		}
	}
	else
	{
		$need_restart = 1;
	}

	if ($need_restart)
	{
		print "Restarting apache in $dir - segfault detected in logs.\n";
		system("$dir/stop");
		sleep(4);
		system("$dir/start");

		chomp($hostname = `hostname`);
		open(OUT, "|/usr/sbin/sendmail -fsysmon\@mst.edu -t");
		print OUT "To: nneul\@mst.edu, esigler\@mst.edu\n";
		print OUT "Subject: Restarting apache in $dir on $hostname\n";
		print OUT "\n";
		close(OUT);
	}
}

